FROM python:3.11-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /opt/dagster/app
COPY pyproject.toml uv.lock ./
COPY mlops_platform/ ./mlops_platform/

RUN uv sync --frozen --no-cache

ENV DAGSTER_HOME=/opt/dagster/dagster_home
CMD ["uv", "run", "dagster", "dev", "-h", "0.0.0.0", "-p", "3000"]